tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "asdf"
brew "bat"
brew "coreutils"
brew "curl"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "howdoi"
brew "htop"
brew "hyperfine"
brew "jq"
brew "kafkacat"
brew "m-cli"
brew "mas"
brew "ncdu"
brew "neovim"
brew "pgcli"
brew "ripgrep"
brew "siege"
brew "starship"
brew "telnet"
brew "tig"
brew "tmux"
brew "travis"
brew "tree"
brew "unzip"
brew "vegeta"
brew "yarn"
brew "z"
brew "zsh"
brew "d12frosted/emacs-plus/emacs-plus"

cask "adoptopenjdk"
cask "appcleaner"
cask "authy"
cask "betterzip"
cask "charles"
cask "dash"
cask "dbeaver-community"
cask "fork"
cask "gas-mask"
cask "karabiner-elements"
cask "postman"
cask "spectacle"
cask "spotify"
cask "transmission"
cask "tunnelblick"
cask "virtualbox"
cask "vlc"
cask "whatsapp"

cask "font-fira-code"
cask "font-ia-writer-duo"
cask "font-ia-writer-duospace"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-iosevka"
cask "font-source-code-pro"
cask "font-victor-mono"

mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Helium", id: 1054607607
